name: Python autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: choose test set
        required: true
        type: choice
        default: smoke
        options:
          - smoke
          - regression
          - all

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run autotests
    steps:
      - name: Checkout autotests
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Install system dependencies for browsers
        run: python -m playwright install-deps

      - name: Install Playwright browsers
        run: python -m playwright install

      - name: Run ALL tests
        if: github.event.inputs.deployment_target == 'all'
        run: pytest --alluredir=allure-results
        continue-on-error: true

      - name: Run SMOKE tests
        if: github.event.inputs.deployment_target == 'smoke'
        run: pytest -m smoke --alluredir=allure-results
        continue-on-error: true

      - name: Run REGRESSION tests
        if: github.event.inputs.deployment_target == 'regression'
        run: pytest -m regression --alluredir=allure-results
        continue-on-error: true

      - name: Store allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 1
  
  generate-report:
    runs-on: ubuntu-latest
    needs: run-tests
    name: Generate report
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'

      - run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.tgz
          tar -zxvf allure-2.24.0.tgz -C /opt/
          sudo ln -s /opt/allure-2.24.0/bin/allure /usr/bin/allure

      - name: Download allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - run: allure generate -c allure-results -o _site

      - name: Store generated report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: _site
          retention-days: 1

  publish-report:
    runs-on: ubuntu-latest
    needs: generate-report
    name: Report publication
    steps:
      - name
